### ISSUE TITLE
现在新版135里cubegeo.faces是undefined

### ISSUE THREAD

**Issue by void1005** [newbieYoung/Threejs_rubik#5]
![image](https://user-images.githubusercontent.com/90739112/145176888-4daa0a16-4512-4c75-87af-a0245008037c.png)

如图所示, 我在最新版里发现`cubegeo.faces`是个undefined, 会报错

改成作者用的的96版本之后打印发现length为12

![image](https://user-images.githubusercontent.com/90739112/145177293-7165e978-64fa-464b-b5b5-954e41f841f8.png)

我不太明白为什么是12, 如果是面的话, 立方体不应该只有6个面吗

**Comment by void1005** [comment]
我挨个测试了一下, 发现这个属性在124上还有, 125就没了

然后我发现, 似乎把这段代码注释掉也没啥影响, 因为反正下面的opacity设置的是0
默认是白色, 改成黑色的话, 有啥特殊用途吗
```js
    // for (var i = 0; i < cubegeo.faces.length; i += 2) {
    //   cubegeo.faces[i].color.setHex(hex);
    //   cubegeo.faces[i + 1].color.setHex(hex);
    // }
```

**Comment by newbieYoung** [comment]
应该是调试代码，背景也是白色，调试的时候看不出来



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月8日(周三) 下午5:47
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [newbieYoung/Threejs_rubik] 现在新版135里cubegeo.faces是undefined (Issue #5)




 
我挨个测试了一下, 发现这个属性在124上还有, 125就没了
 
然后我发现, 似乎把这段代码注释掉也没啥影响, 因为反正下面的opacity设置的是0
 默认是白色, 改成黑色的话, 有啥特殊用途吗
     // for (var i = 0; i < cubegeo.faces.length; i += 2) {     //   cubegeo.faces[i].color.setHex(hex);     //   cubegeo.faces[i + 1].color.setHex(hex);     // }
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by newbieYoung** [comment]
faces 是三角形，六个矩形面，需要 12 个三角形面 @void1005

**Comment by void1005** [comment]
哦哦哦, 三角形我明白了, 感谢作者的回复
